server.port=8081
spring.application.name=main-service

metrics.time-limit-ms=2000
cache.seconds=300

#spring.datasource.url=jdbc:postgresql://localhost:5432/project-t1
#spring.datasource.username=postgres
#spring.datasource.password=12345
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2

spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9094
spring.kafka.consumer.group-id=main-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

metric.kafka.topic=t1_demo_metrics
kafka.topics.accept=t1_demo_transaction_accept

metric.limit.ms=2000

analysis-service.base-url: http://localhost:8081
analysis-service.username: analysis
analysis-service.password: pass123